# Generated by Django 4.2.13 on 2024-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(related_name='news', to='news.category'),
        ),
    ]
